[package]
name = "flash_chain"
version = "0.1.0"
edition = "2024"

[dependencies]
reth-chainspec = { workspace = true }
reth-cli = { workspace = true }
reth-cli-util = { workspace = true }
reth-rpc-eth-api = { workspace = true }
reth-node-api = { workspace = true }
reth-node-builder = { workspace = true }
reth-errors = { workspace = true }
reth-optimism-node = { workspace = true }
reth-optimism-cli = { workspace = true }
reth-optimism-rpc = { workspace = true }
reth-optimism-forks = { workspace = true }
reth-optimism-chainspec = { workspace = true }
reth-optimism-payload-builder = { workspace = true }
reth-optimism-primitives = { workspace = true }
reth-trie-db = { workspace = true }
reth-trie-common = { workspace = true }
reth-rpc-eth-types = { workspace = true }
reth-primitives-traits = { workspace = true }
reth-provider = { workspace = true }
reth-storage-api = { workspace = true }
reth-tracing = { workspace = true }
reth-transaction-pool = { workspace = true }
reth-network = { workspace = true }
reth-network-types = { workspace = true }
reth-chain-state = { workspace = true }

clap = { workspace = true }
tracing = { workspace = true } 

flash-chainspec = { path = "../crates/flash-chainspec" }  
flash-batcher = { path = "../crates/flash-batcher" } 